[alias]
tt = "nextest"
tuni = "test --lib"
tuni-cov = "llvm-cov --html --lib"
te2e = "test --tests"
te2e-cov = "llvm-cov --html --tests"

[build]
target-dir = ".local/build/rust"

[cargo-new]
vcs = "git"

