[cursor]
vi_mode_style = "None"

[cursor.style]
blinking = "On"
shape = "Beam"

[font]
size = 11.0

[font.normal]
family = "monospace"

[scrolling]
history = 5000

[selection]
save_to_clipboard = true

[window]
dynamic_padding = false
dynamic_title = true

[window.dimensions]
columns = 150
lines = 35

[window.padding]
x = 4
y = 4
