theme = "gruvbox"

[editor]
line-number = "absolute"
bufferline = "always"
shell = ["zsh", "-c"]
mouse = true
auto-info = true

color-modes = true
true-color = true
auto-pairs = true

auto-completion = false
completion-trigger-len = 3
completion-replace = true

rulers = [80]
text-width = 80

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.whitespace.render]
space = "none"
tab = "none"
newline = "none"

[editor.whitespace.characters]
space = "·"
tab = "→"
newline = "⏎"

[editor.soft-wrap]
enable = true

[editor.statusline]
left = ["mode", "spinner", "file-name", "file-modification-indicator", "version-control"]
center = []
right = ["workspace-diagnostics", "selections", "position", "file-encoding", "file-type"]
separator = ""
mode.normal = "NOR"
mode.insert = "INS"
mode.select = "SEL"

[editor.lsp]
enable = true
display-messages = true
auto-signature-help = true


# Normal mode
[keys.normal]
ins = "insert_mode"
esc = ["keep_primary_selection", "normal_mode"]
# b = "window_mode"

## Movement
up = "move_line_up"
down = "move_line_down"
left = "move_char_left"
right = "move_char_right"
pageup = "half_page_up"
pagedown = "half_page_down"
home = "goto_line_start"
S-home = ["goto_line_start", "move_next_word_start", "move_char_right"]
end = "goto_line_end_newline"

S-up = "scroll_up"
S-down = "scroll_down"

C-left = "move_prev_word_start"
C-right = "move_next_word_start"

## Commands
C-s = ":write"
s = ":update"
w = ":buffer-close"
c = ":clipboard-yank"
v = ":clipboard-paste-before"
x = [":clipboard-yank", "delete_selection"]

## Operations
tab = "indent"
S-tab = "unindent"
u = "undo"
y = "redo"

## Open picker
C-p = "file_picker"

## Change
del = "delete_selection"
d = "delete_selection"
ret = "insert_newline"
C-k = "toggle_comments"
"~" = "switch_case"

## Selection
e = "select_mode"
l = "extend_line_below"
a = "select_all"
f = "select_regex"

A-up = "expand_selection"
A-down = "shrink_selection"
A-left = "select_prev_sibling"
A-right = "select_next_sibling"

C-S-up = ["extend_to_line_bounds", ":clipboard-yank", ":clipboard-paste-before"]
C-S-down = ["extend_to_line_bounds", ":clipboard-yank", ":clipboard-paste-after"]

S-A-up = ["extend_to_line_bounds", ":clipboard-yank", "delete_selection", "move_line_up", ":clipboard-paste-before"]
S-A-down = ["extend_to_line_bounds", ":clipboard-yank", "delete_selection", ":clipboard-paste-after"]

## Jump
C-tab = "goto_next_buffer"
C-S-tab = "goto_previous_buffer"


# Space mode
[keys.normal.space]
ins = "normal_mode"
esc = "normal_mode"

## Picker
p = "file_picker"
"?" = "command_palette"
b = "buffer_picker"
j = "jumplist_picker"
s = "symbol_picker"
S-s = "workspace_symbol_picker"
d = "diagnostics_picker"
S-d  = "workspace_diagnostics_picker"

## LSP
r = "rename_symbol"
a = "code_action"
h = "hover"
x = "select_references_to_symbol_under_cursor"

## Reset
w = "no_op"
P = "no_op"
y = "no_op"
Y = "no_op"
R = "no_op"

# Goto mode
[keys.normal.g]
ins = "normal_mode"
esc = "normal_mode"

## File
home = "goto_file_start"
end = "goto_file_end"
tab = "goto_next_buffer"
S-tab = "goto_previous_buffer"

## Code
d = "goto_definition"
t = "goto_type_definition"
r = "goto_reference"
i = "goto_implementation"

## Reset
e = "no_op"
f = "no_op"
h = "no_op"
l = "no_op"
s = "no_op"
c = "no_op"
b = "no_op"
y = "no_op"
a = "no_op"
m = "no_op"


# Window/buffer mode
[keys.normal.b]
ins = "normal_mode"
esc = "normal_mode"

q = "wclose"

## Create split
C-right = "vsplit"
C-down = "hsplit"

## Swap split
S-right = "swap_view_right"
S-left = "swap_view_left"
S-up = "swap_view_up"
S-down = "swap_view_down"

## Move split
tab = "rotate_view"
right = "jump_view_right"
left = "jump_view_left"
up = "jump_view_up"
down = "jump_view_down"


# Match mode
[keys.normal.m]
esc = ["keep_primary_selection", "normal_mode"]
ins = "normal_mode"

s = "surround_add"
r = "surround_replace"
d = "surround_delete"
a = "no_op"
i = "no_op"


# Extend mode
[keys.select]
esc = ["keep_primary_selection", "normal_mode"]
ins = "normal_mode"
ret = "normal_mode"


# Insert mode
[keys.insert]
esc = "normal_mode"
ins = "normal_mode"

## Movement
up = "move_line_up"
down = "move_line_down"
left = "move_char_left"
right = "move_char_right"
pageup = "half_page_up"
pagedown = "half_page_down"
home = "goto_line_start"
S-home = ["goto_line_start", "move_next_word_start", "move_char_right"]
end = "goto_line_end_newline"

S-up = "scroll_up"
S-down = "scroll_down"

C-left = "move_prev_word_start"
C-right = "move_next_word_start"

## Change
backspace = "delete_char_backward"
del = "delete_char_forward"
# FIXME: to use some key bindings such as "Ctrl-Backspace" the terminal
# must support the "Enhanced Keyboard Protocol"
C-backspace = "delete_word_backward"
C-del = "delete_word_forward"

## LSP
C-space = "completion"

## Reset
A-backspace = "no_op"

